const data = {
    products:[
        {
            _id: '1',
            name: 'Nike Slim shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            countInStock:10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Adidas Fit Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 120,
            countInStock:20,
            brand: 'Adidas',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Lacoste Free shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 220,
            countInStock:0,
            brand: 'Nike',
            rating: 4.8,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Nike Slim Pant',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 130,
            countInStock:50,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Puma Slim Pant',
            category: 'Pants',
            image: '/images/p5.jpg',
            price: 65,
            countInStock:5,
            brand: 'Puma',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Adidas Slim Pant',
            category: 'Shirts',
            image: '/images/p6.jpg',
            price: 139,
            countInStock:12,
            brand: 'Adidas',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
    ],
};

export default data;